blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Si es una duda general sobre GitHub, preguntar por aquí.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Informar sobre vulnerabilidades generales de GitHub por aquí.
